vich_uploader:
    db_driver: orm

    mappings:
        courses:
            uri_prefix: /ressources/courses
            upload_destination: '%kernel.project_dir%/public/ressources/courses'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        epreuves:
            uri_prefix: /ressources/epreuves
            upload_destination: '%kernel.project_dir%/public/ressources/epreuves'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        corrigetypes:
            uri_prefix: /ressources/corrige_types
            upload_destination: '%kernel.project_dir%/public/ressources/corrige_types'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        tds:
            uri_prefix: /ressources/tds
            upload_destination: '%kernel.project_dir%/public/ressources/tds'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
