vich_uploader:
    db_driver: orm

    mappings:
        epreuves:
            uri_prefix: /ressources/epreuves
            upload_destination: '%kernel.project_dir%/public/ressources/epreuves'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
